name: CI Report
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    name: Report on Unit Tests
    runs-on: ubuntu-latest
    steps:
      - id: report
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Unit Test Results
          path: results-report.json
          reporter: mocha-json
      - run: |
          echo ":white_check_mark: ${{ steps.report.outputs.passed }} passed / :x: ${{ steps.report.outputs.failed }} failed / :white_circle: ${{ steps.report.outputs.skipped }} skipped" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[View Full Report](${{ steps.report.outputs.url_html }})" >> $GITHUB_STEP_SUMMARY